name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Remove old build directory
      run: |
        if [ -d "build" ]; then
          rm -r build
        fi

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1

    - name: Configure CMake
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Run the program
      run: ./build/ip_filter

    - name: Check formatting with clang-format (optional)
      run: |
        sudo apt-get install -y clang-format
        clang-format --version
        clang-format -i main.cpp ip_filter.cpp
        git diff --exit-code
