name: CMake Build, Test and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libboost-test-dev

    - name: Clean CMake build cache
      run: rm -rf build
      shell: bash

    - name: Configure CMake
      run: cmake -S . -B build
      shell: bash

    - name: Build the project
      run: cmake --build build --config Release
      shell: bash

    - name: List build directory
      run: ls -la build/  # Этот шаг выведет содержимое папки build, чтобы увидеть имя файла

    - name: Package binaries
      run: |
        mkdir -p release
        cp build/your_real_executable release/
      shell: bash

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: your_project_name-binaries
        path: release/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0.${{ github.run_number }}
        release_name: Release v1.0.${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload binaries to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release/your_real_executable
        asset_name: your_project_name-executable
        asset_content_type: application/octet-stream
